manifest:
  version: 0.12

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      repo-path: zephyr
      revision: v4.3.0
      import:
        name-allowlist:
          - hal_espressif
          - cmsis
          - mbedtls
          - tinycrypt
          - esp-idf
          - fatfs
          - mcuboot
          - picolibc
          - littlefs

  self:
    path: app
