name: Pico Firmware CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build pico_firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential libnewlib-arm-none-eabi

      - name: Configure CMake
        working-directory: pico_firmware
        run: cmake -S . -B build

      - name: Build
        working-directory: pico_firmware
        run: cmake --build build
