name: Pico Firmware CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build pico_firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential libnewlib-arm-none-eabi g++-arm-none-eabi libstdc++-arm-none-eabi-newlib libgcc-9-dev-arm-none-eabi libnewlib-dev

      - name: Configure CMake
        working-directory: pico_firmware
        run: cmake -S . -B build_pico_w -DPICO_BOARD=pico_w -DMCU_TYPE=cortex-m0

      - name: Build
        working-directory: pico_firmware
        run: cmake --build build_pico_w
