name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_target:
    name: Build and Test Targets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Debug contents
      run: |
        echo "Listing root of repo:"
        ls -la
        echo "Listing pico_firmware:"
        ls -la pico_firmware || echo "pico_firmware not found"
        echo "Listing FreeRTOS-Kernel:"
        ls -la FreeRTOS-Kernel || echo "FreeRTOS-Kernel not found"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install ARM GCC toolchain and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make cmake

    - name: Build for pico_w (cortex-m0)
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico_firmware/external/pico-sdk
        PICO_TOOLCHAIN_PATH: /usr/bin
      run: |
        cd pico_firmware  # Change to pico_firmware directory
        cmake -S . -B build_pico_w -DPICO_BOARD=pico_w -DMCU_TYPE=cortex-m0
        cmake --build build_pico_w

    - name: Build for pico2_w (cortex-m33)
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/external/pico-sdk
        PICO_TOOLCHAIN_PATH: /usr/bin
      run: |
        cd pico_firmware  # Change to pico_firmware directory
        cmake -S . -B build_pico2_w -DPICO_BOARD=pico2_w -DPICO_PLATFORM=rp2350 -DMCU_TYPE=cortex-m33
        cmake --build build_pico2_w
