name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_target:
    name: Build and Test Targets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Force update submodule URLs to HTTPS
      run: |
        # Remove the existing submodule configuration to ensure it will be reconfigured
        git submodule deinit -f --all
        git submodule update --init --recursive

        # Update submodule URLs to HTTPS
        git submodule foreach --recursive '
        git config submodule.$name.url https://github.com/furhadjidda/$name.git
        '
    - name: Initialize submodules
      run: git submodule update --init --recursive --depth 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install ARM GCC toolchain and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make cmake

    - name: Build for pico_w (cortex-m0)
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/external/pico-sdk
        PICO_TOOLCHAIN_PATH: /usr/bin
      run: |
        cd pico_firmware  # Change to pico_firmware directory
        cmake -S . -B build_pico_w -DPICO_BOARD=pico_w -DMCU_TYPE=cortex-m0
        cmake --build build_pico_w -- -j8

    - name: Build for pico2_w (cortex-m33)
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/external/pico-sdk
        PICO_TOOLCHAIN_PATH: /usr/bin
      run: |
        cd pico_firmware  # Change to pico_firmware directory
        cmake -S . -B build_pico2_w -DPICO_BOARD=pico2_w -DPICO_PLATFORM=rp2350 -DMCU_TYPE=cortex-m33
        cmake --build build_pico2_w -- -j8
